# Generated by Django 5.1.4 on 2024-12-06 01:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AppGDP', '0008_remove_inventario_responsavel'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sala',
            name='quantidade_itens',
        ),
    ]
