# Generated by Django 5.1.4 on 2024-12-07 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppGDP', '0010_alter_sala_descricao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sala',
            name='descricao',
            field=models.CharField(max_length=255),
        ),
    ]
